services:
    anime_db.shikimori.browser:
        class: AnimeDb\Bundle\ShikimoriBrowserBundle\Service\Browser
        arguments: [ '@anime_db.shikimori.browser.client', ~, ~ ]

    anime_db.shikimori.browser.client:
        class: GuzzleHttp\Client
        public: false
