services:
    anime_db.shikimori.browser:
        class: AnimeDb\Bundle\ShikimoriBrowserBundle\Service\Browser
        arguments:
            - %anime_db.shikimori.host%
            - %anime_db.shikimori.api.host%
            - %anime_db.shikimori.api.prefix%